

###   Logistic 回归（因变量为类别型）

```{r}
library(AER)  #install.packages("AER")
data("Affairs",package = "AER")
summary(Affairs)
table(Affairs$affairs)

Affairs$yn[Affairs$affairs>0]<-1
Affairs$yn[Affairs$affairs==0]<-0
Affairs$yn<-factor(Affairs$yn,levels = c(0,1),labels = c("No","Yes"))

table(Affairs$yn)

fit1<-glm(yn~gender+age+yearsmarried+children+
          religiousness+education+occupation+rating,
          data=Affairs,family = binomial(link = logit)
          )
summary(fit1)

fit2<-glm(yn~age+yearsmarried+religiousness+rating,
         data=Affairs,family = binomial(link = logit)
)
summary(fit2)

anova(fit2,fit1,test = "Chisq") #两模型嵌套（fit2是fit1的子集） 
#卡方值不显著，两模型拟合效果无显著差异


log<-coef(fit2)  #回归系数  对数优势 log（odds）
exp(log)        #指数化   odds

#评价预测变量对结果概率的影响
testdata<-data.frame(rating=c(1,2,3,4,5),age=mean(Affairs$age),
                     yearsmarried=mean(Affairs$yearsmarried),
                     religiousness=mean(Affairs$religiousness))
testdata
testdata$prob<-predict(fit2,newdata = testdata,type = "response")
testdata

#过度离势   Φ=deviance()/df.residual()
deviance(fit2)/df.residual(fit2)  #接近1，表明不存在过度离势
fit.od<-glm(yn~age+yearsmarried+religiousness+rating,
            data=Affairs,family =quasibinomial(link = logit))
#过度离势的检验 H0：Φ=1
pchisq(summary(fit.od)$dispersion*fit2$df.residual,
       fit2$df.residual,lower=F)                     #P>0.05




```




### 泊松回归（因变量为计数型）

```{r}
library(robust)
data("breslow.dat")
names(breslow.dat)
breslow.dat
summary(breslow.dat[,c(6,7,8,10)])

opar<-par(no.readonly = TRUE)
par(mfrow=c(1,2))                    
hist(breslow.dat$sumY,breaks = 20)
boxplot(breslow.dat$sumY~breslow.dat$Trt,data = breslow.dat,varwidth=TRUE,
        col=c("gold","darkgreen"),
        main="Group Comparisons",
        xlab="Treatment")

fit3<-glm(sumY~Base+Age+Trt,data=breslow.dat,family = poisson(link = "log"))
summary(fit3)

coef(fit3)
exp(coef(fit3))

#过度离势   Φ=deviance()/df.residual()
deviance(fit3)/df.residual(fit3)  #  >>1，表明存在过度离势

#过度离势的检验 H0：Φ=1
install.packages("qcc")
library(qcc)
qcc.overdispersion.test(breslow.dat$sumY,type = "poisson")  # P<0.05


```

### 类泊松分布

```{r}
fit.od2<-glm(sumY~Base+Age+Trt,data=breslow.dat,family = quasipoisson(link = "log"))
summary(fit.od2)
```

