---
title: "统计描述"
format: html
editor: visual
---

# 统计描述

```{r}
mtcars$mpg
```

## 集中趋势和离散程度

```{r}
mean(mtcars$mpg)     #算术均数
# 几何均数 G=^n^√X1X2...Xn
median(mtcars$mpg)   #中位数
quantile(mtcars$mpg,probs = c(0,0.1,0.25,0.5,0.75,1))     #分位数



range(mtcars$mpg)  # 值域
diff(range(mtcars$mpg) )  # 极差
IQR(mtcars$mpg)      # 四分位数间距
sd(mtcars$mpg)       #标准差
var(mtcars$mpg)      #方差
CV=sd(mtcars$mpg)/mean(mtcars$mpg)*100  # 变异系数
paste(CV,"%")



mad(mtcars$mpg,constant = 1.4826)      #绝对中位差 median absolute deviation

median(abs(mtcars$mpg-median(mtcars$mpg)))
median(abs(mtcars$mpg-median(mtcars$mpg)))*1.4826
```

为了达到渐进正态一致性，`mad()` 的计算乘了一个比例因子`constant=1.4826`。

## 偏度和峰度

term

:   [^1]偏度（Skewness）的计算公式：

    $$ 
    S = \frac{n}{(n-1)(n-2)} \sum_{i=1}^{n} \left( \frac{X_i-\overline{X}}{SD} \right)^3 ]
    $$[^2] 峰度（Kurtosis）的计算公式：

    $$
    K = \frac{n(n+1)}{(n-1)(n-2)(n-3)}  \sum_{i=1}^{n} \left( \frac{X_i - \overline{X}}{SD} \right)^4  - \frac{3(n-1)^2}{(n-2)(n-3)}
    $$

[^1]: WPS Excel

[^2]: WPS Excel

```{r}
skewness <- function(x,na.rm=TRUE){
    if(na.rm) x <- x[!is.na(x)]
    n=length(x)
    μ=mean(x)
    SD=sd(x)
    sknewness = sum((x-μ)^3/SD^3)*n/((n-1)*(n-2))
    return(sknewness=sknewness)
}
skewness(c(21.4,5.4,23.5,21.4,44.3,14.9))

kurtosis<-function(x,na.rm=TRUE){
    if(na.rm) x<-x[!is.na(x)]
    n=length(x)
    μ=mean(x)
    SD=sd(x)
    kurtosis=sum((x-μ)^4/SD^4)*n*(n+1)/((n-1)*(n-2)*(n-3))-(3*(n-1)^2)/((n-2)*(n-3))
    return(kurtosis=kurtosis)
}

kurtosis(c(21.4,5.4,23.5,21.4,44.3,14.9))
```

## 频数表和列联表

```{r}
data(gss_cat)  #因子数据集
head(gss_cat)
```

```{r}
table(gss_cat$marital,gss_cat$race)
tbl <- xtabs(~marital+race,data = gss_cat)
tbl
```

```{r}
prop.table(tbl)          #各单元格比例
prop.table(tbl,margin = 1)        #行比例 
margin.table(x=tbl,margin = 2)      #列和

 
addmargins(tbl)          #添加行和、列和
addmargins(tbl,1)        #添加列和
addmargins(tbl,2)        #添加行和
addmargins(prop.table(tbl,1))

ftable(tbl)   # "平铺式"列联表
```

## 独立性检验（分类变量）

独立性：无关联或非线性关联

```{r}
M <- as.table(rbind(c(762, 327, 468), c(484, 239, 477)))
dimnames(M) <- list(gender = c("F", "M"),
                    party = c("Democrat","Independent", "Republican"))
M
#   1. 卡方检验
chisq <- chisq.test(M)
chisq$parameter # degrees of freedom

#   2. Fisher精确检验   Fisher's exact test to test independence of rows and columns in contingency table
fisher.test(M)


Rabbits <-
array(c(0, 0, 6, 5,
        3, 0, 3, 6,
        6, 2, 0, 4,
        5, 6, 1, 0,
        2, 5, 0, 0),
      dim = c(2, 2, 5),
      dimnames = list(
          Delay = c("None", "1.5h"),
          Response = c("Cured", "Died"),
          Penicillin.Level = c("1/8", "1/4", "1/2", "1", "4")))
Rabbits
#   3. Cochran-Mantel-Haenszel 卡方检验  两个变量在第三个变量的每一水平下是否独立
mantelhaen.test(Rabbits)
```

## 相关性检验（定量变量）

相关性：线性关联

```{r}
states <- state.x77[,1:6]
cov(states)    # 协方差矩阵
```

#### 相关系数

```{r}
# Pearson's 积差相关系数
cor(states,use = "everything",method="pearson") # default

# Spearman's rank相关系数
cor(states,method = "spearman")

# Kendall's tau相关系数
cor(states,method = "kendall")
```

#### 相关图（correlogram）

@sec-correlogram

#### 显著性检验

```{r}
cor.test(state.x77[,"Income"],state.x77[,"Illiteracy"])
```

psych包`corr.test()` 计算相关矩阵和显著性水平

**多分格（polychoric）相关系数**、**多系列（polyserial）相关系数**

#### 偏相关系数

在控制其他变量的条件下，分析两个定量变量之间的相关关系

ggm包`pcor()` , `pcor.test()`

## 数据可视化

[基础绘图](03_base_graphics.qmd)

[ggplot2绘图](04_ggplot2_graphics.qmd)
