# 线性混合效应模型

[Mixed Effects Models and Extensions in Ecology with R 第5章](https://link.springer.com/book/10.1007/978-0-387-87458-6)

限制最大似然法，REML

赤池信息准则AIC

贝叶斯信息准则BIC

线性混合模型，LME的表达式如下：

$$
fit=lmer (data,formual= DV ~ Fixed\_Factor + (Random\_intercept + Random\_slope | Random\_Factor))
$$

截距中，1表示随机截距，0表示固定截距，默认截距为1。

| LME                         | 表达式             | 简写             |
|-----------------------------|--------------------|------------------|
| 随机截距+随机斜率           | y\~x+( 1+x \| id ) | y\~x+( x \| id ) |
| 随机截距+固定斜率           | y\~x+( 1+1 \| id ) | y\~x+( 1 \| id ) |
| 固定截距+随机斜率           | y\~x+( 0+x \| id ) | NA               |
| 线性模型：固定截距+固定斜率 | y\~x               | NA               |

```{r}
library(lme4)
library(nlme)
df_long <- read_delim("data/AED/RIKZ.txt")
df_long$Beach <- factor(df_long$Beach)
df_long$Exposure <- factor(df_long$Exposure)
str(df_long)
```

## 随机截距+随机斜率

$$
\eta_{(nrow \ \times 1)}=\mathbf{X_{nrow×1}}\beta_{1\times1} +Z_{nrow\times 2n_{subjects}} \mathbf{\gamma}_{2n_{subjects}\times 1}+\epsilon_i
$$

Z有两倍于受试者数量的列，每个受试者的随机截距和随机斜率

```{r}
lme1 <- lmer(Richness ~ 1 + NAP * Exposure+ (1 +NAP |Beach) ,data = df_long)
summary(lme1)
AIC(lme1)
BIC(lme1)
logLik(lme1)

2*(1-pt(-3.914605,35,lower.tail = F))



# nlme1 <- lme(Richness ~ 1 + NAP * Exposure,random= ~ 1+NAP |Beach ,data = df_long)
# summary(nlme1)


```

```{r}
# 标准化模型残差分布
quantile(residuals(lme1,type="pearson",scaled=T))

# 随机因子随机效应和显著性检验
ranef(lme1)
lmerTest::ranova(lme1)

# 查看固定效应和显著性检验
coef(lme1)
anova(lme1)

#  查看 类和方法
class(lme1)
methods(class = "lmerMod")

# confint(lme1,level = 0.95)
```

## 随机截距+固定斜率

$$
\eta_{(nrow \ \times 1)}=\mathbf{X_{nrow×1}}\beta_{1\times1} +Z_{nrow\times n_{subjects}} \mathbf{\gamma}_{n_{subjects}\times 1}+\epsilon_i
$$

Z有一倍于受试者数量的列，每个受试者的随机截距。

```{r}
lme2 <- lmer(Richness ~ 1 + NAP+ (1 |Beach) ,data = df_long)
summary(lme2)
AIC(lme2)
BIC(lme2)
logLik(lme2)

2*(1-pt(6.007,35,lower.tail = T))



nlme2 <- lme(Richness ~ 1 + NAP * Exposure,random= ~ 1 |Beach ,data = df_long)
summary(nlme2)
```

## 固定截距+随机斜率

```{r}
lme3 <- lmer(Richness ~ 1 + NAP+ (0 + NAP |Beach) ,data = df_long)
summary(lme3)

nlme3 <- lme(Richness ~ 1 + NAP,random= ~ 0+NAP |Beach ,data = df_long)
summary(nlme3)
```

## 随机效应模型

```{r}
nlme4 <- lme(Richness ~ 1 ,random= ~ 1 |Beach ,data = df_long)
summary(nlme4)
```

## 线性模型：固定截距+ 固定斜率

```{r}
lm4 <- lm(Richness ~ 1 + NAP ,data = df_long)
lm4
```

## 模型选择

```{r}

plot_lme <- function(model, title) {
    ggplot(df_long, aes(NAP, Richness, group = Beach, color = Beach)) +
        geom_point() +
        geom_line(
            data =  bind_cols(df_long, .pred = predict(model, df_long)),
            mapping = aes(y = .pred),
            linewidth = 1
        ) +
        labs(title = title)+
        scale_x_continuous(expand = (mult=c(0,.1)))+
        scale_y_continuous(expand = (mult=c(0,.1)))+
    ggsci::scale_color_jco() +
        ggpubr::theme_pubr() +
        theme(legend.position = "right",
              plot.title = element_text(hjust = .5))
}


lme_plot <- map2(list(lme1,lme2,lme3,lm4),list("随机截距+随机斜率","随机截距+固定斜率","固定截距+随机斜率","固定截距+固定斜率"),plot_lme)


lme_plot
```

```{r}
anova(lme1,lme2,lme3)
anova(lme1,lme2,lme3,lm4)

# p小于0.05,说明全模型与简化后模型存在差异，最终采用lme1,AIC最小
```
