# 非参数秩检验

排序

$$
F(Median)=P(X\le Median)=0.5
$$

二项分布B（n，0.5）

```{r}
ggplot() + xlim(-10,10) +
    geom_function(mapping = aes(color="normal Distribution"),
                  fun = dnorm, args = list(mean = 5, sd = 1),
                   )+
    geom_function(mapping = aes(color="binomial Distribution"),
                  fun = dbinom, args = list(size=10 ,prob=0.5), 
                 )+
    scale_color_manual(values = c("normal Distribution" = "red",
                                  "binomial Distribution" = "blue"))+
    labs(color = "Distribution")
```

## 单样本Wilcoxon Signed-Rank 检验

如果样本数据没有通过正态分布检验就要采用单样本wilcoxon符号秩检验进行计算。使用该检验需要满足的条件是样本值均匀地分布在均值两侧。

```{r}
x<- dplyr::filter(PlantGrowth,group=="ctrl")
shapiro.test(x$weight)
summary(x$weight)
wilcox.test(x$weight, mu=7) 
```

## 配对 Wilcoxon's signed-rank 检验

$$
T_++T_-=\frac{n(n+1)}{2},n为非零配对差值的数量
$$

$$
T=min{(T_+,T_-)}
$$

5 ≤ n ≤30，附表T~0~

n＞16，正态近似法

```{r}

df <- tibble(
    low=c(958.5,838.4,612.2,812.9,739.0,899.4,758.5,695.0,749.7,815.5),
    high=c(958.5,866.5,788.9,815.2,783.2,910.9,760.8,870.8,862.3,799.9),
)

shapiro.test(df$high-df$low)

# 忽略 差值为0
wilcox.test(df$low[-1],df$high[-1],exact = T,paired = T)
```

## 独立双样本Wilcoxon's Rank-Sum 检验

当两个样本不满足正态分布时，使用Wilcoxon秩和检验进行非参数检验

$$
T=T_{min(n1,n2)}=T_1
$$

```{r}
MVR = c(38, 29, 35, 33, 38, 41, 31)
MVP = c(32, 43, 44, 81, 35, 46, 37, 45, 44)
shapiro.test(c(MVR,MVP))

combined_data <- c(MVR, MVP)
ranked_data <- rank(combined_data)
ranked_data 

MVR_ranks <- ranked_data[1:length(MVR)]
MVP_ranks <- ranked_data[(length(MVR)+1):length(combined_data)]

T1 <- sum(MVR_ranks)
T2 <- sum(MVP_ranks)

W <- T1-length(MVR)*(length(MVR)+1)/2
```

$$
W=T_1-\frac{n_1(n_1+1)}{2}
$$

n1\<10,n2-n1\<10，附录

n1\>10,n2\>10，正态近似法

```{r}
wilcox.test(MVR,MVP,exact = F,correct = F)
```

```{r}


ggplot() + xlim(0,50) +
    geom_function(mapping = aes(color="Wilcox Distribution"),
                  fun = dwilcox, args = list(m=7 ,n=9), 
                 )+
    scale_color_manual(values = c("Wilcox Distribution" = "blue"))+
    labs(color = "Distribution")



```

## 独立多样本Kruskal-Wallis 检验

假设：

1.  随机，独立

2.  每个样本至少5个观测

3.  能够计算秩次

```{r}
kruskal.test(weight~group,data = PlantGrowth)
```

### 多重比较

```{r}
pairwise.wilcox.test(PlantGrowth$weight,PlantGrowth$group,p.adjust.method = "fdr",exact=F)
```

## 随机区组设计方差分析

```{r eval=FALSE}
friedman.test()
```
